### ISSUE TITLE
Sidebar Duplicates Indefinitely

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#14]
I don't know if this only happens with me but I'm at a WP MS + BP system and when I go to customize the sidebar duplicates inside of itself indefinitely which stalls the site.

The only way I have to work in it is removing the sidebar completely

**Comment by buddycore** [comment]
I know this is a little bit strange to me, seen this also. 

Let me take a look into this a little more.

**Comment by buddycore** [comment]
Furthermore to this i've looked into a few things with Customizer for themes and there's a known bug / conflict with jQuery UI which is used for the sidebar area in Surface. 

With further investigation I learned that some general functionality expected with WordPress is unavailable due to whatever type of restriction with WordPress.

Also, I implemented live preview of colours as picked and applied to the theme in customizer, this was very slow and caused the browser to lock up.

So, I can't do much with the sidebar for now. 

I've left colour picker as is but it's going to need a hard refresh for previewing.
