### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#15]
Is groups finished or a work in process? There are different bugs in groups.

At group creation first step, button full width or not? In other parts of the theme you use full width button.

At group creation, you are not allowed to upload neither logo neither cover and you don't have finish creation button.

**Comment by buddycore** [comment]
For creating group creation the buttons I think should be as they are, I can't see a reason to have a full width "Next Step" button only to have a full width "Previous Step" button when available.

Having those links side by side makes practical sense to me. 

The layout changes a small amount to accommodate the avatar and cover image uploads because that's the layout that sits on both member profiles and group pages when modifying these settings. It's not perfect but I can live with this for now. 

Maybe you could do a mockup of how you think it should be for me to look at? I could look at it again and take it from there.

I just checked my local copy both avatar and cover image for groups at group creation does work. You might want to check your specific settings in wp-admin for BuddyPress.

**Comment by Wemago** [comment]
Yep it works. Forgot of buddypress settings sorry. Now the bug is if you have those settings off (cover+photo) you do not have finish group creation button, probably this bug comes from buddypress itself.

**Comment by buddycore** [comment]
No you were right I messed up the logic. Should be better now.
