### ISSUE TITLE
Activity plus now does not work on form in groups.

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#31]
I have a comment on these two issues: https://github.com/buddycore/surface-theme/issues/27 and https://github.com/buddycore/surface-theme/issues/9

Activity plus now does not work on form in groups.

**Comment by buddycore** [comment]
Yes, I don't know why this is behaving like this. The same code powers both member and group forms on the front-end.

You could create a post on https://wordpress.org/support/plugin/buddypress-activity-plus to find out why maybe and come back to me with what I need to do.

**Comment by inzerat** [comment]
Ok i create https://wordpress.org/support/topic/activity-plus-now-does-not-work-on-form-in-groups/

**Comment by inzerat** [comment]
Here is reply https://wordpress.org/support/topic/activity-plus-now-does-not-work-on-form-in-groups/#post-8252110 I dont know still - why?

**Comment by buddycore** [comment]
Ok i've identified the problem partially, when a front.php file is present the BuddyPress Activity Plus will never show in the groups activity page.

So I've removed that for now, but this means we lose the home page for groups which is a core BuddyPress feature.

When running the twenty sixteen theme there was no conflict and the BuddyPress Activity Plus would show on both activity and group activity. That's because it uses bp-legacy templates, which by default doesn't have a front.php file.

Could you report this BuddyPress Activity Plus here https://wordpress.org/support/topic/activity-plus-now-does-not-work-on-form-in-groups/#post-8252110 and tell me what their reply is.

So, for now... 

If you want the form to show in both activity stream and group activity stream, simple rename the file front.php to front.bak and keep it until we get a solution from BuddyPress Activity Plus.

You can find this file in wp-content/themes/surface/buddypress/groups/single/front.php

Hope that helps, not perfect but I think this maybe on BuddyPress Activity Plus to make their plugin compatible when a front.php file is present in the active theme.

**Comment by buddycore** [comment]
I seen the low quality response on the wordpress.org support forums for bpap. This is why I don't really want to support plugins. Maybe in the months ahead I will write a better upload plugin for members and groups.
