### ISSUE TITLE
Better UX for reply of comments

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#74]
# **New:**
![new](https://cloud.githubusercontent.com/assets/21200726/20866844/618c3526-ba37-11e6-8673-7a4e5f33995c.png)
# **Old:**
![old](https://cloud.githubusercontent.com/assets/21200726/20866845/618eb666-ba37-11e6-9b2b-10bce2895d73.png)

**Comment by buddycore** [comment]
I will be dropping support for Surface for the forseeable future and focussing on Centro. Which aims to tackle some of the main problems in Surface.

Customizer functionality with Surface is cripped because of a bug with WordPress and jQuery... Given the bug affects a large part of Surface (the sidebar) it's hard for me to re-imagine the design with a static sidebar with no tabbing.

That said, I may return to this and create a new alternative sidebar for Surface.

For now, my efforts are with Centro which may be of interest to you in the future.

Thanks for using Surface, keep checking buddycore.com for updates.
